// ============================================================
// SEO Keyword Pages Data — 200 High-Value Keywords
// ============================================================

export interface KeywordPage {
  slug: string
  title: string
  h1: string
  metaDescription: string
  intro: string
  sections: {
    heading: string
    content: string
  }[]
  relatedSlugs: string[]
}

// Helper to generate consistent page content
function kw(
  slug: string,
  title: string,
  h1: string,
  metaDesc: string,
  intro: string,
  sections: { heading: string; content: string }[],
  relatedSlugs: string[] = []
): KeywordPage {
  return { slug, title, h1, metaDescription: metaDesc, intro, sections, relatedSlugs }
}

export const keywordPages: KeywordPage[] = [
  // ── CRANE RENTAL (1-15) ──────────────────────────
  kw("crane-rental-uae", "Crane Rental UAE", "Crane Rental Services in UAE", "Rent mobile cranes in UAE — 25 ton & 50 ton cranes available. Certified operators, fast delivery. Hadeed Transport.", "Hadeed Transport provides reliable crane rental services across the UAE. Our fleet includes 25-ton and 50-ton mobile cranes, maintained to the highest standards and operated by certified professionals. Whether you need a crane for a single lift or a long-term project, we deliver on time and on budget.", [{ heading: "Our Crane Fleet", content: "We maintain a diverse fleet of mobile cranes ranging from 25-ton to 50-ton capacity. Each crane undergoes rigorous safety inspections and is equipped with the latest safety features including load moment indicators, anti-two-block systems, and outrigger monitoring." }, { heading: "Professional Crane Operations", content: "Every crane rental comes with a certified operator experienced in UAE construction environments. Our operators follow strict safety protocols and are trained in the latest lifting procedures." }, { heading: "Flexible Crane Rental Terms", content: "We offer daily, weekly, and monthly crane rental options. Whether you need a crane for a single day's lift or a six-month project, our flexible terms ensure you get the best value." }], ["crane-rental-abu-dhabi", "crane-rental-dubai", "50-ton-crane-rental"]),

  kw("crane-rental-abu-dhabi", "Crane Rental Abu Dhabi", "Crane Rental in Abu Dhabi", "Rent cranes in Abu Dhabi — 25 & 50 ton mobile cranes with operators. Same-day delivery from ICAD III. Hadeed Transport.", "Based in ICAD III, Hadeed Transport provides fast crane rental services across Abu Dhabi. Our mobile cranes are available for construction, industrial, and infrastructure projects with same-day delivery capability.", [{ heading: "Same-Day Crane Delivery in Abu Dhabi", content: "Operating from our ICAD III base, we can deliver cranes to any location in Abu Dhabi within hours. Our logistics team ensures your crane arrives on time, every time." }, { heading: "Abu Dhabi Crane Rental Rates", content: "We offer competitive crane rental rates in Abu Dhabi with transparent pricing. No hidden charges — just reliable equipment and professional service at fair prices." }], ["crane-rental-uae", "crane-rental-dubai", "25-ton-crane-rental"]),

  kw("crane-rental-dubai", "Crane Rental Dubai", "Crane Rental Services in Dubai", "Rent mobile cranes in Dubai — 25 & 50 ton capacity. Professional operators, fast delivery across all Dubai areas. Hadeed Transport.", "Hadeed Transport delivers crane rental services to all areas of Dubai. From Downtown to Jebel Ali, our mobile cranes support high-rise construction, steel erection, and heavy lifting operations across the city.", [{ heading: "Crane Services Across Dubai", content: "We serve all major Dubai areas including Downtown, Business Bay, Dubai Marina, JLT, DIFC, and industrial zones like DIP and Jebel Ali. Our fleet is strategically positioned for fast response times." }, { heading: "Dubai Construction Crane Solutions", content: "Dubai's skyline demands reliable lifting solutions. Our 25-ton and 50-ton mobile cranes handle everything from residential tower construction to commercial high-rise projects." }], ["crane-rental-uae", "crane-rental-abu-dhabi", "50-ton-crane-rental"]),

  kw("25-ton-crane-rental", "25 Ton Crane Rental", "25 Ton Mobile Crane for Rent in UAE", "Rent a 25 ton mobile crane in Abu Dhabi & Dubai. Certified operator included. Fast delivery. Hadeed Transport.", "Our 25-ton mobile crane is the versatile workhorse of construction sites. Ideal for medium-duty lifting operations, steel erection, and material handling, this crane delivers reliable performance with a certified operator.", [{ heading: "25 Ton Crane Specifications", content: "Our 25-ton mobile cranes feature telescopic booms with extended reach, 360-degree rotation, and advanced safety systems. The compact footprint makes them suitable for sites with limited space." }, { heading: "Applications for 25 Ton Cranes", content: "Perfect for residential construction, commercial building projects, industrial installations, and infrastructure work. The 25-ton capacity handles most construction lifting requirements efficiently." }], ["50-ton-crane-rental", "crane-rental-uae"]),

  kw("50-ton-crane-rental", "50 Ton Crane Rental", "50 Ton Mobile Crane for Rent in UAE", "Rent a 50 ton mobile crane in Abu Dhabi & Dubai. Heavy lifting capacity with certified operator. Hadeed Transport.", "When your project demands serious lifting power, our 50-ton mobile crane delivers. Designed for heavy-duty construction, industrial installations, and major infrastructure projects across the UAE.", [{ heading: "50 Ton Crane Capabilities", content: "Our 50-ton mobile crane handles the heaviest construction loads with precision. From placing heavy steel beams to lifting pre-cast concrete elements, this crane gets the job done safely and efficiently." }, { heading: "Heavy Lifting Projects", content: "Ideal for high-rise construction, bridge building, industrial plant erection, and large-scale infrastructure projects. The 50-ton capacity ensures you can handle even the most demanding lifts." }], ["25-ton-crane-rental", "crane-rental-uae"]),

  kw("tower-crane-rental-uae", "Tower Crane Rental UAE", "Tower Crane Rental Services in UAE", "Tower crane rental in Abu Dhabi & Dubai. Professional erection, operation & dismantling. Long-term contracts available. Hadeed Transport.", "For high-rise construction projects that require continuous lifting at height, our crane solutions provide the power and reach needed. We support tower crane operations with our mobile crane fleet for assembly and support lifting.", [{ heading: "Supporting Tower Crane Operations", content: "While we specialize in mobile cranes, our equipment supports tower crane assembly, maintenance, and operations. Our mobile cranes assist with tower crane erection and dismantling." }, { heading: "Long-Term Project Support", content: "We offer long-term crane rental contracts for major construction projects requiring sustained lifting operations over months or years." }], ["crane-rental-uae", "50-ton-crane-rental"]),

  // ── EXCAVATOR & EARTHMOVING (16-30) ──────────────
  kw("excavator-rental-uae", "Excavator Rental UAE", "Excavator Rental Services in UAE", "Rent excavators in UAE — backhoe loaders, shovels & mini excavators. Certified operators, fast delivery. Hadeed Transport.", "Hadeed Transport offers a comprehensive range of excavation equipment for rent across the UAE. From compact backhoe loaders to large shovels, our earthmoving fleet handles projects of every scale.", [{ heading: "Excavation Equipment Fleet", content: "Our fleet includes shovels of various sizes, backhoe loaders, JCB machines, and bobcat mini loaders. Each machine is maintained to peak operating condition and available with certified operators." }, { heading: "Earthmoving Capabilities", content: "Whether you're excavating foundations, trenching for utilities, or grading terrain, our excavation equipment delivers the digging force and precision your project demands." }], ["excavator-rental-abu-dhabi", "excavator-rental-dubai", "backhoe-loader-rental"]),

  kw("excavator-rental-abu-dhabi", "Excavator Rental Abu Dhabi", "Excavator Rental in Abu Dhabi", "Rent excavators in Abu Dhabi. Backhoe loaders, shovels & earthmoving machinery. Same-day delivery from ICAD III. Hadeed Transport.", "Hadeed Transport provides fast excavator delivery across Abu Dhabi from our ICAD III base. Our earthmoving equipment supports construction, infrastructure, and utility installation projects throughout the emirate.", [{ heading: "Abu Dhabi Excavation Services", content: "From residential foundation excavation in Khalifa City to industrial earthworks in Mussafah, our excavators are ready for deployment across all Abu Dhabi areas." }, { heading: "Same-Day Equipment Delivery", content: "Need an excavator today? Our ICAD III location enables same-day delivery to most Abu Dhabi locations. Contact us early for guaranteed same-day availability." }], ["excavator-rental-uae", "excavator-rental-dubai"]),

  kw("excavator-rental-dubai", "Excavator Rental Dubai", "Excavator Rental Services in Dubai", "Rent excavators in Dubai — all sizes available. Backhoe loaders, shovels & mini excavators. Fast delivery. Hadeed Transport.", "From major development sites in Dubai South to renovation projects in Jumeirah, Hadeed Transport delivers excavation equipment to every corner of Dubai. Our fleet handles everything from precision trenching to large-scale earthmoving.", [{ heading: "Dubai Excavation Solutions", content: "Dubai's continuous growth demands reliable excavation equipment. We supply backhoe loaders, shovels, and compact excavators for residential, commercial, and infrastructure projects across the city." }], ["excavator-rental-uae", "excavator-rental-abu-dhabi"]),

  kw("backhoe-loader-rental", "Backhoe Loader Rental", "Backhoe Loader for Rent in UAE", "Rent JCB backhoe loaders in Abu Dhabi & Dubai. Various sizes for trenching, excavation & loading. Hadeed Transport.", "The backhoe loader is one of the most versatile machines on any construction site. Hadeed Transport offers JCB backhoe loaders and excavators of various sizes for rent across the UAE.", [{ heading: "Versatile Backhoe Loaders", content: "Our backhoe loaders combine excavation and loading capabilities in one machine. Perfect for trenching, backfilling, material handling, and general earthwork on construction sites." }, { heading: "JCB Equipment Quality", content: "We maintain JCB backhoe loaders known for their reliability, efficiency, and operator comfort. Regular servicing ensures optimum performance on your project." }], ["excavator-rental-uae", "jcb-rental-uae"]),

  kw("jcb-rental-uae", "JCB Rental UAE", "JCB Machine Rental in UAE", "Rent JCB machines in Abu Dhabi & Dubai — backhoe loaders & excavators. Well-maintained fleet, certified operators. Hadeed Transport.", "JCB machines are the backbone of construction earthwork. Hadeed Transport offers well-maintained JCB backhoe loaders for trench excavation, general earthwork, and material handling projects across the UAE.", [{ heading: "JCB Backhoe Loader Fleet", content: "Our JCB fleet handles limited to medium-size excavation work including trenching, utility installation, and site preparation. Available in various sizes to match your project needs." }], ["backhoe-loader-rental", "excavator-rental-uae", "bobcat-rental-uae"]),

  kw("bobcat-rental-uae", "Bobcat Rental UAE", "Bobcat Mini Loader for Rent in UAE", "Rent Bobcat mini loaders in Abu Dhabi & Dubai. Ideal for tight spaces & earthwork. Fast delivery. Hadeed Transport.", "When you need earthmoving capability in limited access areas, our Bobcat mini loaders are the perfect solution. Compact yet powerful, these machines handle confined-space excavation across the UAE.", [{ heading: "Compact Earthmoving Power", content: "Bobcat mini loaders excel in tight spaces where larger equipment can't access. Ideal for indoor demolition, landscaping, basement work, and confined construction areas." }], ["excavator-rental-uae", "jcb-rental-uae"]),

  kw("earth-moving-equipment-rental", "Earth Moving Equipment Rental", "Earthmoving Equipment for Rent in UAE", "Rent earthmoving equipment in UAE — shovels, excavators, loaders & graders. Complete fleet for site preparation. Hadeed Transport.", "Hadeed Transport provides a complete range of earthmoving equipment for construction site preparation, road building, and terrain grading across Abu Dhabi and Dubai.", [{ heading: "Complete Earthmoving Fleet", content: "From shovels and excavators to backhoe loaders and bobcats, our earthmoving fleet covers every aspect of site preparation. We match the right machine size to your project requirements." }, { heading: "Site Preparation Services", content: "Our earthmoving equipment handles foundation excavation, terrain grading, trench digging, and backfilling. Available with certified operators for safe and efficient operations." }], ["excavator-rental-uae", "construction-equipment-rental-uae"]),

  kw("shovel-rental-uae", "Shovel Rental UAE", "Shovel Rental for Earthwork in UAE", "Rent shovels in various sizes for earthwork in Abu Dhabi & Dubai. Heavy-duty excavation equipment. Hadeed Transport.", "Hadeed Transport offers shovels of various sizes for earth-moving and excavation projects across the UAE. Our shovel fleet handles large-volume earthwork efficiently with certified operators.", [{ heading: "Shovel Capabilities", content: "Our shovels are designed for heavy-duty earthwork including site excavation, material loading, and large-scale earth moving operations. Available in multiple sizes for different project scales." }], ["excavator-rental-uae", "earth-moving-equipment-rental"]),

  // ── FORKLIFT (31-40) ──────────────────────────────
  kw("forklift-rental-uae", "Forklift Rental UAE", "Forklift Rental Services in UAE", "Rent forklifts 1-15 ton in UAE. Diesel & electric models. Warehouse & construction site delivery. Hadeed Transport.", "Hadeed Transport offers forklifts from 1 ton to 15 ton capacity for material handling across the UAE. Our fleet includes diesel and electric models for warehouses, construction sites, and industrial facilities.", [{ heading: "Forklift Fleet Range", content: "Choose from 1-ton compact forklifts for warehouse work to 15-ton heavy-duty units for construction sites. Diesel models for outdoor use and electric models for indoor operations." }, { heading: "Industrial Material Handling", content: "Our forklifts handle pallets, containers, construction materials, and industrial loads with precision. Available for short-term daily rental or long-term monthly contracts." }], ["forklift-rental-abu-dhabi", "forklift-rental-dubai"]),

  kw("forklift-rental-abu-dhabi", "Forklift Rental Abu Dhabi", "Forklift Rental in Abu Dhabi", "Rent forklifts in Abu Dhabi — 1 to 15 ton capacity. Same-day delivery from ICAD III. Hadeed Transport.", "Need a forklift in Abu Dhabi? Hadeed Transport delivers forklifts of all sizes from our ICAD III base. Same-day delivery available for urgent material handling requirements.", [{ heading: "Abu Dhabi Forklift Solutions", content: "We serve warehouses in Mussafah, construction sites across Khalifa City, logistics operations in KIZAD, and industrial facilities throughout Abu Dhabi with reliable forklift rental services." }], ["forklift-rental-uae", "forklift-rental-dubai"]),

  kw("forklift-rental-dubai", "Forklift Rental Dubai", "Forklift Rental Services in Dubai", "Rent forklifts in Dubai — all capacities from 1 to 15 tons. Fast delivery to all Dubai areas. Hadeed Transport.", "From Jebel Ali's logistics hubs to Dubai Investment Park's warehouses, Hadeed Transport delivers forklifts across all Dubai areas for material handling and warehouse operations.", [{ heading: "Dubai Forklift Delivery", content: "We deliver forklifts to all Dubai areas including DIP, Jebel Ali, Al Quoz, Dubai Industrial City, and all commercial and industrial zones across the city." }], ["forklift-rental-uae", "forklift-rental-abu-dhabi"]),

  kw("warehouse-forklift-rental", "Warehouse Forklift Rental", "Warehouse Forklift for Rent in UAE", "Rent warehouse forklifts in UAE — electric & diesel models. 1-15 ton capacity for logistics operations. Hadeed Transport.", "Efficient warehouse operations require reliable forklifts. Hadeed Transport offers electric and diesel forklifts specifically suited for warehouse material handling across the UAE.", [{ heading: "Electric Forklifts for Warehouses", content: "Our electric forklifts are ideal for indoor warehouse operations — zero emissions, low noise, and precise handling for pallet movement and racking operations." }], ["forklift-rental-uae"]),

  // ── GENERATOR (41-55) ─────────────────────────────
  kw("generator-rental-uae", "Generator Rental UAE", "Generator Rental Services in UAE", "Rent generators 10-500 KVA in UAE. Construction, events & emergency power. Fast delivery. Hadeed Transport.", "Hadeed Transport provides reliable generator rental services from 10 KVA to 500 KVA across the UAE. Power your construction site, event, or facility with our well-maintained diesel generators.", [{ heading: "Generator Capacity Range", content: "Our generators range from portable 10 KVA units for small tools and lighting to powerful 500 KVA units for large construction sites and industrial operations. Every generator is fuel-efficient and regularly serviced." }, { heading: "24/7 Power Solutions", content: "We provide round-the-clock technical support for generator rentals. If your generator needs attention, our maintenance team responds rapidly to minimize downtime." }], ["generator-rental-abu-dhabi", "generator-rental-dubai", "500-kva-generator-rental"]),

  kw("generator-rental-abu-dhabi", "Generator Rental Abu Dhabi", "Generator Rental in Abu Dhabi", "Rent generators in Abu Dhabi — 10 to 500 KVA. Same-day delivery. Construction & event power solutions. Hadeed Transport.", "Power up your Abu Dhabi project with Hadeed Transport's generator rental services. Same-day delivery from ICAD III for construction sites, events, and emergency backup power.", [{ heading: "Abu Dhabi Power Solutions", content: "From construction sites in Yas Island to industrial operations in Mussafah, we deliver generators across all Abu Dhabi locations with same-day availability." }], ["generator-rental-uae", "generator-rental-dubai"]),

  kw("generator-rental-dubai", "Generator Rental Dubai", "Generator Rental Services in Dubai", "Rent generators in Dubai — all capacities from 10-500 KVA. Construction, events & emergency power. Hadeed Transport.", "Hadeed Transport delivers generators to all Dubai areas for construction power, event electricity, and emergency backup. Our fleet ranges from 10 KVA portables to 500 KVA industrial units.", [{ heading: "Dubai Generator Solutions", content: "We power construction projects across Dubai from Downtown high-rises to Dubai South developments. Our generators are delivered, installed, and supported with 24/7 technical assistance." }], ["generator-rental-uae", "generator-rental-abu-dhabi"]),

  kw("500-kva-generator-rental", "500 KVA Generator Rental", "500 KVA Generator for Rent in UAE", "Rent 500 KVA generators in Abu Dhabi & Dubai. Heavy-duty power for large construction sites. Hadeed Transport.", "Our 500 KVA generators are built for large-scale construction sites and industrial operations that demand high-capacity, continuous power generation across the UAE.", [{ heading: "Heavy-Duty Power Generation", content: "The 500 KVA generator handles the power demands of major construction projects, large events, and industrial facilities. Sound-attenuated enclosures ensure low-noise operation." }], ["generator-rental-uae", "250-kva-generator-rental"]),

  kw("250-kva-generator-rental", "250 KVA Generator Rental", "250 KVA Generator for Rent in UAE", "Rent 250 KVA generators in UAE. Medium to large construction site power. Fast delivery. Hadeed Transport.", "The 250 KVA generator is ideal for medium to large construction sites requiring substantial power. Hadeed Transport delivers and supports these units across Abu Dhabi and Dubai.", [{ heading: "Medium-Large Power Solution", content: "With 250 KVA capacity, this generator powers multiple power tools, site lighting, cranes, and temporary offices simultaneously. A popular choice for commercial construction projects." }], ["generator-rental-uae", "500-kva-generator-rental"]),

  kw("portable-generator-rental", "Portable Generator Rental", "Portable Generator for Rent in UAE", "Rent portable generators 10-60 KVA in UAE. Compact power for small sites & events. Hadeed Transport.", "Need portable power? Our 10 to 60 KVA generators are compact, fuel-efficient, and easy to deploy for small construction sites, events, and remote locations.", [{ heading: "Compact Power On Demand", content: "Our portable generators range from 10 KVA to 60 KVA — perfect for powering hand tools, lighting, small equipment, and temporary facilities. Easy to transport and set up." }], ["generator-rental-uae"]),

  kw("construction-site-generator-rental", "Construction Site Generator", "Construction Site Generator Rental in UAE", "Rent construction site generators in UAE. Reliable power for tools, lighting & operations. 10-500 KVA. Hadeed Transport.", "Every construction site needs reliable power. Hadeed Transport provides generators specifically configured for construction environments — powering tools, cranes, lighting, and temporary offices.", [{ heading: "Site-Ready Power", content: "Our construction generators come pre-configured with distribution boards and cabling for easy site integration. From small residential sites to major commercial projects, we have the right power solution." }], ["generator-rental-uae"]),

  kw("event-generator-rental-uae", "Event Generator Rental UAE", "Event Generator Rental in UAE", "Rent event generators in Abu Dhabi & Dubai. Quiet operation, reliable power for outdoor events. Hadeed Transport.", "Power your outdoor event, exhibition, or festival with Hadeed Transport's event-grade generators. Sound-attenuated enclosures ensure low noise while providing reliable electricity.", [{ heading: "Event Power Solutions", content: "Our event generators feature whisper-quiet enclosures, automatic voltage regulation, and large fuel tanks for uninterrupted operation. Perfect for concerts, exhibitions, weddings, and corporate events." }], ["generator-rental-uae"]),

  kw("emergency-generator-rental", "Emergency Generator Rental", "Emergency Generator Rental in UAE", "Emergency generator rental in Abu Dhabi & Dubai. Rapid deployment for power outages. 24/7 service. Hadeed Transport.", "When power fails, Hadeed Transport delivers. Our emergency generator rental service provides rapid deployment of backup power units across the UAE — available 24/7.", [{ heading: "Rapid Emergency Response", content: "Power outages can't wait. Our emergency generators are pre-staged and ready for rapid deployment to hospitals, data centers, commercial facilities, and construction sites across the UAE." }], ["generator-rental-uae"]),

  // ── TRANSPORT VEHICLES (56-70) ────────────────────
  kw("pickup-truck-rental-uae", "Pickup Truck Rental UAE", "Pickup Truck Rental in UAE", "Rent pickup trucks in UAE — 1, 2 & 3 ton pickups with drivers. Material & worker transportation. Hadeed Transport.", "Hadeed Transport offers 1-ton, 2-ton, and 3-ton pickup trucks for rent across the UAE. Ideal for material transportation, worker movement, and general cargo delivery with experienced drivers.", [{ heading: "Pickup Fleet", content: "Our pickup fleet includes 1-ton, 2-ton, and 3-ton vehicles suitable for various cargo sizes. Each pickup comes with an experienced driver familiar with UAE roads and traffic." }, { heading: "Flexible Transport Solutions", content: "Whether you need a single pickup for a day or a fleet for a long-term project, we offer flexible rental terms at competitive rates." }], ["pickup-truck-rental-abu-dhabi", "pickup-truck-rental-dubai"]),

  kw("pickup-truck-rental-abu-dhabi", "Pickup Rental Abu Dhabi", "Pickup Truck Rental in Abu Dhabi", "Rent pickup trucks in Abu Dhabi — 1, 2 & 3 ton. Drivers included. Same-day dispatch from ICAD III. Hadeed Transport.", "Need materials delivered in Abu Dhabi? Our pickup trucks are available with drivers for same-day dispatch from ICAD III to any location across the emirate.", [{ heading: "Abu Dhabi Pickup Services", content: "We serve all Abu Dhabi areas with reliable pickup truck transportation. From construction material delivery to equipment transport, our drivers handle it professionally." }], ["pickup-truck-rental-uae", "pickup-truck-rental-dubai"]),

  kw("pickup-truck-rental-dubai", "Pickup Rental Dubai", "Pickup Truck Rental in Dubai", "Rent pickup trucks in Dubai — 1, 2 & 3 ton capacity with drivers. Fast delivery across all areas. Hadeed Transport.", "Hadeed Transport delivers pickup truck rental services across all Dubai areas. Our 1-3 ton pickups handle material transport, site deliveries, and worker transportation.", [{ heading: "Dubai Pickup Delivery", content: "We dispatch pickups to all Dubai locations including Downtown, DIP, Jebel Ali, Al Quoz, and beyond. Our drivers know Dubai's roads for efficient delivery." }], ["pickup-truck-rental-uae", "pickup-truck-rental-abu-dhabi"]),

  kw("bus-rental-uae", "Bus Rental UAE", "Bus Rental for Worker Transport in UAE", "Rent buses in UAE — 12, 15, 30 & 60 seater. Worker & staff transport with professional drivers. Hadeed Transport.", "Transport your workforce safely and efficiently with Hadeed Transport's bus rental services. We offer 12 to 60 seater buses with professional drivers across the UAE.", [{ heading: "Bus Fleet Options", content: "Choose from 12-seater minibuses, 15-seater vans, 30-seater buses, or 60-passenger coaches. All vehicles are air-conditioned and maintained for passenger safety and comfort." }, { heading: "Worker Transportation Services", content: "We specialize in daily worker transportation from labor camps to construction sites. Flexible scheduling to match your shift patterns, 7 days a week." }], ["bus-rental-abu-dhabi", "bus-rental-dubai"]),

  kw("bus-rental-abu-dhabi", "Bus Rental Abu Dhabi", "Bus Rental for Staff Transport in Abu Dhabi", "Rent buses in Abu Dhabi — 12 to 60 seats. Worker & staff transport with drivers. Daily & monthly. Hadeed Transport.", "Reliable staff transportation in Abu Dhabi. Our buses transport workers from camps to construction sites daily, with professional drivers and air-conditioned comfort.", [{ heading: "Daily Worker Transport in Abu Dhabi", content: "We operate daily bus routes between labor camps and construction sites across Abu Dhabi, including ICAD, Mussafah, Yas Island, and all major project areas." }], ["bus-rental-uae", "bus-rental-dubai"]),

  kw("bus-rental-dubai", "Bus Rental Dubai", "Bus Rental Services in Dubai", "Rent buses in Dubai — all sizes with professional drivers. Worker transport, events & corporate. Hadeed Transport.", "From construction worker shuttles to corporate staff buses, Hadeed Transport provides bus rental services across all Dubai areas with professional, licensed drivers.", [{ heading: "Dubai Bus Solutions", content: "Our buses serve construction sites, corporate offices, events, and airport transfers across Dubai. Multiple seating options from 12 to 60 passengers." }], ["bus-rental-uae", "bus-rental-abu-dhabi"]),

  kw("water-tanker-rental-uae", "Water Tanker Rental UAE", "Water Tanker Rental in UAE", "Rent water tankers in UAE — 3000 & 5000 gallon. Construction water supply, dust suppression. Hadeed Transport.", "Hadeed Transport provides 3,000 and 5,000 gallon water tankers for construction site water supply, dust suppression, and irrigation across the UAE.", [{ heading: "Water Supply Solutions", content: "Our water tankers deliver clean water to construction sites for concrete mixing, dust control, compaction, and general site use. Scheduled and on-demand delivery available." }], ["water-tanker-rental-abu-dhabi", "water-tanker-rental-dubai"]),

  kw("water-tanker-rental-abu-dhabi", "Water Tanker Abu Dhabi", "Water Tanker Rental in Abu Dhabi", "Rent water tankers in Abu Dhabi — 3000 & 5000 gallon. Construction water delivery. Hadeed Transport.", "Construction water supply in Abu Dhabi made easy. Our water tankers deliver 3,000 and 5,000 gallons to your project site on schedule.", [{ heading: "Abu Dhabi Water Delivery", content: "We supply water to construction sites across Abu Dhabi for concrete work, dust suppression, and general use. Regular scheduled deliveries or on-demand service available." }], ["water-tanker-rental-uae"]),

  kw("water-tanker-rental-dubai", "Water Tanker Dubai", "Water Tanker Rental in Dubai", "Rent water tankers in Dubai — 3000 & 5000 gallon capacity. Construction & industrial water supply. Hadeed Transport.", "Water delivery to Dubai construction sites and industrial facilities. Our tankers provide reliable water supply for concrete operations, dust control, and landscaping.", [{ heading: "Dubai Water Tanker Service", content: "Fast water delivery to all Dubai areas. Our tanker drivers are experienced and our vehicles are maintained for clean water transportation." }], ["water-tanker-rental-uae"]),

  kw("diesel-tanker-rental", "Diesel Tanker Rental", "Diesel Tanker for Rent in UAE", "Rent diesel tankers in Abu Dhabi & Dubai. Fuel transportation and delivery services. Hadeed Transport.", "Hadeed Transport's diesel tankers provide safe and certified fuel transportation services across the UAE. Ideal for construction site refueling and remote area diesel delivery.", [{ heading: "Safe Fuel Transportation", content: "Our diesel tankers are fully certified for fuel transportation in the UAE. Experienced drivers handle all safety protocols for loading, transport, and delivery of diesel fuel." }], ["water-tanker-rental-uae"]),

  kw("recovery-truck-rental", "Recovery Truck Rental", "Recovery Truck for Rent in UAE", "Rent recovery trucks in Abu Dhabi & Dubai. Equipment & vehicle transport. Various sizes. Hadeed Transport.", "Need to move heavy equipment or stranded vehicles? Our recovery trucks handle machinery transport, vehicle recovery, and equipment relocation across the UAE.", [{ heading: "Equipment Transport Solutions", content: "Our recovery trucks transport heavy machinery, construction equipment, and vehicles safely between sites. Available in various sizes to handle different load requirements." }], ["pickup-truck-rental-uae", "trailer-rental-uae"]),

  kw("trailer-rental-uae", "Trailer Rental UAE", "Trailer Rental for Heavy Transport in UAE", "Rent trailers in UAE for heavy material & equipment transport. Large-capacity solutions. Hadeed Transport.", "For oversized and heavy loads, our trailers provide the transportation capacity you need. Moving large construction materials, equipment, and prefab elements across the UAE.", [{ heading: "Heavy Load Transport", content: "Our trailers handle the largest construction loads — prefab concrete elements, steel structures, heavy machinery, and oversized materials. Professional drivers ensure safe transport." }], ["recovery-truck-rental", "pickup-truck-rental-uae"]),

  // ── MANLIFT & ACCESS (71-80) ──────────────────────
  kw("manlift-rental-uae", "Manlift Rental UAE", "Manlift Rental Services in UAE", "Rent manlifts in UAE — low & high level aerial platforms. Building maintenance & construction. Hadeed Transport.", "Safe access to elevated work areas with Hadeed Transport's manlift rental services. We offer both low-level and high-level aerial platforms for construction, maintenance, and industrial applications.", [{ heading: "Low & High Level Manlifts", content: "Our fleet includes low-level manlifts for work up to 12 meters and high-level platforms for reaching 20+ meters. Battery and diesel models available for indoor and outdoor use." }, { heading: "Safe Elevated Access", content: "Manlifts provide a safer, faster alternative to scaffolding for tasks like painting, electrical work, HVAC installation, and facade maintenance." }], ["manlift-rental-abu-dhabi", "manlift-rental-dubai", "scaffolding-rental-uae"]),

  kw("manlift-rental-abu-dhabi", "Manlift Rental Abu Dhabi", "Manlift Rental in Abu Dhabi", "Rent manlifts in Abu Dhabi — aerial work platforms for construction & maintenance. Same-day delivery. Hadeed Transport.", "Hadeed Transport delivers manlifts across Abu Dhabi for building maintenance, construction access, and industrial operations. Same-day delivery from our ICAD III base.", [{ heading: "Abu Dhabi Aerial Access", content: "From Corniche high-rises to Yas Island attractions, our manlifts provide safe elevated access for maintenance, construction, and installation work across Abu Dhabi." }], ["manlift-rental-uae"]),

  kw("manlift-rental-dubai", "Manlift Rental Dubai", "Manlift Rental Services in Dubai", "Rent manlifts in Dubai — low & high level platforms. Building maintenance & construction access. Hadeed Transport.", "Access Dubai's high-rise towers and commercial buildings safely with our manlift rental services. Low and high level platforms delivered to all Dubai areas.", [{ heading: "Dubai Elevated Access", content: "Our manlifts serve Dubai's construction and maintenance projects from Dubai Marina towers to DIFC commercial buildings. Both low and high level platforms available." }], ["manlift-rental-uae"]),

  kw("boom-lift-rental-uae", "Boom Lift Rental UAE", "Boom Lift for Rent in UAE", "Rent boom lifts in Abu Dhabi & Dubai. Telescopic & articulated models for elevated access. Hadeed Transport.", "Reach over obstacles and access hard-to-reach areas with our boom lift rentals. Telescopic and articulated models available for construction and maintenance across the UAE.", [{ heading: "Boom Lift Solutions", content: "Our boom lifts offer superior reach and flexibility compared to standard vertical platforms. Ideal for reaching over obstacles, working at heights, and accessing areas that scaffolding can't reach." }], ["manlift-rental-uae", "scissor-lift-rental-uae"]),

  kw("scissor-lift-rental-uae", "Scissor Lift Rental UAE", "Scissor Lift for Rent in UAE", "Rent scissor lifts in UAE. Electric & diesel models for indoor/outdoor elevated work. Hadeed Transport.", "For stable elevated work platforms, our scissor lifts provide a large work area at height. Ideal for ceiling work, electrical installation, and warehouse maintenance across the UAE.", [{ heading: "Stable Work at Height", content: "Scissor lifts offer a stable, spacious platform for tasks requiring sustained work at height. Electric models for indoor use and diesel models for outdoor construction sites." }], ["manlift-rental-uae", "boom-lift-rental-uae"]),

  kw("scaffolding-rental-uae", "Scaffolding Rental UAE", "Scaffolding for Rent in UAE", "Rent heavy & light duty scaffolding in UAE. Professional erection & dismantling. Hadeed Transport.", "Hadeed Transport provides heavy-duty and light-duty scaffolding systems for construction projects across the UAE. Complete packages including erection, inspection, and dismantling services.", [{ heading: "Scaffolding Systems", content: "Our scaffolding inventory includes both heavy-duty systems for structural work and light-duty systems for finishing trades. All materials are certified and regularly inspected." }, { heading: "Professional Scaffolding Services", content: "We offer full scaffolding services including design, erection, modification, inspection, and dismantling. Our teams follow UAE safety standards for all installations." }], ["scaffolding-rental-abu-dhabi", "scaffolding-rental-dubai"]),

  kw("scaffolding-rental-abu-dhabi", "Scaffolding Abu Dhabi", "Scaffolding Rental in Abu Dhabi", "Rent scaffolding in Abu Dhabi — heavy & light duty. Erection & dismantling services. Hadeed Transport.", "Professional scaffolding solutions in Abu Dhabi. Heavy and light duty systems for building construction, maintenance, and renovation with full erection services.", [{ heading: "Abu Dhabi Scaffolding", content: "We supply and erect scaffolding for projects across Abu Dhabi including Saadiyat Island cultural projects, Al Reem Island towers, and commercial buildings throughout the city." }], ["scaffolding-rental-uae"]),

  kw("scaffolding-rental-dubai", "Scaffolding Dubai", "Scaffolding Rental in Dubai", "Rent scaffolding in Dubai — complete systems with erection services. Heavy & light duty. Hadeed Transport.", "Scaffolding for Dubai's construction and renovation projects. Complete systems delivered, erected, and maintained to safety standards across all Dubai areas.", [{ heading: "Dubai Scaffolding Solutions", content: "From Downtown skyscrapers to Dubai Marina towers, we provide scaffolding systems engineered for safety and efficiency. Our teams handle everything from delivery to dismantling." }], ["scaffolding-rental-uae"]),

  // ── CONCRETE & TOOLS (81-100) ─────────────────────
  kw("concrete-mixer-rental", "Concrete Mixer Rental", "Concrete Mixer for Rent in UAE", "Rent concrete mixers in UAE — petrol & electric models. Small quantity mixing for construction sites. Hadeed Transport.", "Mix concrete on-site with our reliable concrete mixers. Both petrol and electric models available for construction projects of all sizes across the UAE.", [{ heading: "Petrol & Electric Mixers", content: "Our concrete mixers come in petrol and electric variants. Petrol models are ideal for outdoor sites without power, while electric models suit indoor and powered locations." }], ["concrete-equipment-rental-uae"]),

  kw("concrete-vibrator-rental", "Concrete Vibrator Rental", "Concrete Vibrator for Rent in UAE", "Rent concrete vibrators in UAE — diesel & electric. Professional concrete casting tools. Hadeed Transport.", "Ensure quality concrete placement with our vibrators. Diesel and electric models available for concrete casting and consolidation on construction sites across the UAE.", [{ heading: "Vibrator Options", content: "Choose from diesel-powered vibrators for outdoor and remote sites or electric vibrators for powered locations. Multiple needle sizes available for different section sizes." }], ["concrete-equipment-rental-uae"]),

  kw("concrete-equipment-rental-uae", "Concrete Equipment UAE", "Concrete Equipment Rental in UAE", "Rent concrete mixers, vibrators, power floats & saws in UAE. Complete concrete tool solutions. Hadeed Transport.", "Hadeed Transport provides a full range of concrete equipment for rent — mixers, vibrators, power floats, saw cutters, and more. Everything you need for professional concrete work.", [{ heading: "Complete Concrete Solutions", content: "From mixing to finishing, we have every concrete tool you need. Mixers for batching, vibrators for consolidation, power floats for finishing, and saws for cutting — all available for rent." }], ["concrete-mixer-rental", "concrete-vibrator-rental"]),

  kw("concrete-cutter-rental", "Concrete Cutter Rental", "Concrete Saw Cutter for Rent in UAE", "Rent concrete saw cutters in Abu Dhabi & Dubai. Road cutting, slab cutting & precision concrete work. Hadeed Transport.", "Precision concrete cutting with our professional saw cutters. Ideal for road cutting, expansion joint cutting, and slab modification on construction projects.", [{ heading: "Precision Concrete Cutting", content: "Our concrete saw cutters handle road cutting, slab modification, and expansion joint creation. Water-cooled systems ensure clean cuts with minimal dust." }], ["concrete-equipment-rental-uae"]),

  kw("jack-hammer-rental", "Jack Hammer Rental", "Jack Hammer for Rent in UAE", "Rent jack hammers in Abu Dhabi & Dubai — pneumatic & electric. Concrete breaking & demolition. Hadeed Transport.", "Break concrete efficiently with our professional jack hammers. Available in pneumatic and electric models for demolition, chipping, and concrete removal projects.", [{ heading: "Concrete Breaking Solutions", content: "Our jack hammers come in various sizes for different applications — from light chipping to heavy concrete demolition. Anti-vibration handles reduce operator fatigue." }], ["concrete-equipment-rental-uae", "air-compressor-rental-uae"]),

  kw("plate-compactor-rental", "Plate Compactor Rental", "Plate Compactor for Rent in UAE", "Rent plate compactors in Abu Dhabi & Dubai. Soil & sand compaction for construction. Hadeed Transport.", "Compact soil, sand, and gravel efficiently with our plate compactors. Perfect for trench backfill, paving preparation, and foundation work on construction sites.", [{ heading: "Compact Area Compaction", content: "Plate compactors excel at compacting granular materials in areas where larger rollers can't access. Ideal for patios, walkways, trenches, and tight construction areas." }], ["compaction-equipment-rental", "roller-rental-uae"]),

  kw("compaction-equipment-rental", "Compaction Equipment Rental", "Compaction Equipment for Rent in UAE", "Rent compaction equipment in UAE — rollers, plate compactors & jumping jacks. Road & foundation work. Hadeed Transport.", "Complete compaction solutions from Hadeed Transport — rollers, plate compactors, and jumping jack compactors for road construction, foundation preparation, and earthwork.", [{ heading: "Full Compaction Fleet", content: "From 1-ton walk-behind rollers to 4-ton driving rollers, plus plate compactors and jumping jacks — we have compaction equipment for every application and project size." }], ["roller-rental-uae", "plate-compactor-rental"]),

  kw("roller-rental-uae", "Roller Rental UAE", "Road Roller for Rent in UAE", "Rent road rollers in UAE — 1, 2 & 4 ton. Soil compaction & road construction. Hadeed Transport.", "Hadeed Transport offers vibratory rollers from 1 ton to 4 ton for road construction, sub-base compaction, and earthwork projects across the UAE.", [{ heading: "Roller Fleet", content: "Our roller fleet includes 1-ton and 2-ton walk-behind rollers and 2-ton and 4-ton driving rollers. Vibratory systems deliver efficient compaction for road and earthwork projects." }], ["compaction-equipment-rental"]),

  kw("air-compressor-rental-uae", "Air Compressor Rental UAE", "Air Compressor for Rent in UAE", "Rent air compressors in UAE — 300 & 900 CFM diesel, plus electric models. Hadeed Transport.", "Power your pneumatic tools with our reliable air compressors. Diesel models in 300 and 900 CFM, plus electric compressors for indoor use across the UAE.", [{ heading: "Compressor Range", content: "Our 300 CFM compressors power most pneumatic construction tools, while 900 CFM units handle sandblasting and multiple tools simultaneously. Electric compressors suit indoor applications." }], ["air-compressor-rental-abu-dhabi"]),

  kw("air-compressor-rental-abu-dhabi", "Air Compressor Abu Dhabi", "Air Compressor Rental in Abu Dhabi", "Rent air compressors in Abu Dhabi — diesel & electric. 300-900 CFM. Fast delivery. Hadeed Transport.", "Compressed air solutions in Abu Dhabi from Hadeed Transport. Diesel and electric compressors for construction, cleaning, and industrial operations.", [{ heading: "Abu Dhabi Compressor Services", content: "We deliver air compressors across Abu Dhabi for jack hammer operations, sandblasting, cleaning, and pneumatic tool power. Same-day delivery from our ICAD III base." }], ["air-compressor-rental-uae"]),

  kw("dewatering-pump-rental", "Dewatering Pump Rental", "Dewatering System for Rent in UAE", "Rent dewatering pumps in Abu Dhabi & Dubai. Foundation dewatering, flood management. Hadeed Transport.", "Keep your construction site dry with our dewatering systems. Submersible and surface pumps for foundation dewatering, flood management, and groundwater control.", [{ heading: "Dewatering Solutions", content: "Our dewatering systems include submersible pumps, surface pumps, and complete systems with hoses and fittings. We handle setup and can provide monitoring for critical operations." }], []),

  kw("steel-bending-machine-rental", "Steel Bending Machine", "Steel Bending Machine for Rent in UAE", "Rent steel rebar bending machines in UAE. Electric models for various rebar sizes. Hadeed Transport.", "Process steel reinforcement efficiently with our electric bending machines. Handle various rebar diameters for foundation, beam, and column reinforcement preparation.", [{ heading: "Steel Processing Equipment", content: "Our steel bending machines handle rebar from 8mm to 32mm diameter. Precision angle settings ensure accurate bends every time for professional reinforcement fabrication." }], ["steel-cutter-rental"]),

  kw("steel-cutter-rental", "Steel Cutter Rental", "Steel Cutter for Rent in UAE", "Rent steel rebar cutting machines in UAE. Electric cutters for various sizes. Hadeed Transport.", "Cut steel reinforcement bars quickly and cleanly with our electric cutting machines. Available for all standard rebar sizes used in UAE construction.", [{ heading: "Precision Rebar Cutting", content: "Our steel cutters handle various rebar diameters with clean, accurate cuts. Electric powered for reliable operation on powered construction sites." }], ["steel-bending-machine-rental"]),

  // ── SPACE RENTALS (101-130) ───────────────────────
  kw("warehouse-rental-uae", "Warehouse Rental UAE", "Warehouse for Rent in UAE", "Rent warehouses in Abu Dhabi — 300 to 1000 sqm units. Secure storage & logistics. Located in ICAD III. Hadeed Transport.", "Hadeed Transport offers warehouse space for rent in Abu Dhabi's ICAD III industrial zone. With units from 300 sqm to 1,000 sqm, we have storage for businesses of every size.", [{ heading: "Warehouse Options", content: "Our 6,000 sqm warehouse facility offers individual units from 300 to 1,000 sqm. Options include single large warehouses or multiple smaller units depending on your needs." }, { heading: "Strategic ICAD III Location", content: "Located in Abu Dhabi's premier industrial zone, our warehouses provide easy access to major highways, ports, and the city center." }], ["warehouse-rental-abu-dhabi", "warehouse-rental-dubai"]),

  kw("warehouse-rental-abu-dhabi", "Warehouse Abu Dhabi", "Warehouse for Rent in Abu Dhabi", "Rent warehouse space in Abu Dhabi — ICAD III location. 300-1000 sqm units. Secure, accessible. Hadeed Transport.", "Secure warehouse rental in Abu Dhabi's ICAD III. Our facilities offer 300 to 1,000 sqm units with 24/7 access, security, and excellent road connectivity.", [{ heading: "Abu Dhabi Warehouse Location", content: "Strategically located in ICAD III with direct access to Abu Dhabi's highway network. Ideal for logistics, distribution, manufacturing, and general storage operations." }], ["warehouse-rental-uae"]),

  kw("warehouse-rental-dubai", "Warehouse Dubai", "Warehouse for Rent near Dubai", "Warehouse rental near Dubai — strategic Abu Dhabi location with highway access. 300-1000 sqm. Hadeed Transport.", "Looking for warehouse space near Dubai? Our ICAD III facility in Abu Dhabi offers competitive rates with strategic highway access connecting to Dubai in under an hour.", [{ heading: "Strategic Location for Dubai Access", content: "Our Abu Dhabi warehouses provide a cost-effective alternative to Dubai warehouse rates while maintaining excellent highway connectivity to all Dubai areas." }], ["warehouse-rental-uae"]),

  kw("office-space-rental-uae", "Office Space Rental UAE", "Office Space for Rent in UAE", "Rent office spaces in Abu Dhabi. Open-plan & closed offices for businesses. Business center facilities. Hadeed Transport.", "Hadeed Transport offers functional office spaces for rent in Abu Dhabi. Open-plan and closed configurations suitable for businesses, contractors, and project offices.", [{ heading: "Office Configurations", content: "Choose from open-plan offices for collaborative teams or closed offices for private operations. Business center facilities include shared amenities for professional operations." }], ["office-space-rental-abu-dhabi"]),

  kw("office-space-rental-abu-dhabi", "Office Space Abu Dhabi", "Office Space for Rent in Abu Dhabi", "Office space for rent in Abu Dhabi — open-plan & private. Business center facilities. Competitive rates. Hadeed Transport.", "Professional office space in Abu Dhabi at competitive rates. Suitable for contractors, project teams, and businesses needing functional workspace.", [{ heading: "Abu Dhabi Office Solutions", content: "Our office spaces cater to construction companies, project managers, and businesses needing affordable, functional workspace in Abu Dhabi's industrial area." }], ["office-space-rental-uae"]),

  kw("storage-rental-uae", "Storage Rental UAE", "Self-Storage for Rent in UAE", "Rent self-storage units in Abu Dhabi — 30 to 100 sqm. Secure, clean & accessible. Hadeed Transport.", "Secure self-storage solutions in Abu Dhabi. Around 32 storage units ranging from 30 sqm to 100 sqm for personal and business storage needs.", [{ heading: "Self-Storage Units", content: "Our self-storage facility offers approximately 32 units in sizes from 30 to 100 sqm. Clean, secure, and easily accessible for both personal and business storage." }], ["storage-rental-abu-dhabi"]),

  kw("storage-rental-abu-dhabi", "Storage Abu Dhabi", "Self-Storage Units in Abu Dhabi", "Rent self-storage in Abu Dhabi — 32 units from 30-100 sqm. Daily storage solutions. Hadeed Transport.", "Self-storage in Abu Dhabi for individuals and businesses. Our 32 units offer sizes from 30 to 100 sqm with daily access and secure facilities.", [{ heading: "Abu Dhabi Storage Options", content: "Whether you need temporary storage during a move, inventory overflow space, or document archiving facilities, our self-storage units provide clean and secure solutions." }], ["storage-rental-uae"]),

  kw("open-yard-rental-uae", "Open Yard Rental UAE", "Open Yard for Rent in UAE", "Rent open yards in Abu Dhabi — up to 25,000 sqm. Heavy equipment storage, staging & logistics. Hadeed Transport.", "Large open yard spaces available in Abu Dhabi for equipment storage, material staging, and logistics operations. Areas up to 25,000 sqm available.", [{ heading: "Expansive Open Yards", content: "Our open yards provide up to 25,000 sqm of space for heavy equipment storage, material staging, vehicle parking, and industrial operations in Abu Dhabi." }], ["open-yard-rental-abu-dhabi"]),

  kw("open-yard-rental-abu-dhabi", "Open Yard Abu Dhabi", "Open Yard for Rent in Abu Dhabi", "Rent open yard space in Abu Dhabi — up to 25,000 sqm. Equipment storage & staging. Hadeed Transport.", "Open yard rental in Abu Dhabi for construction equipment storage, material staging, and vehicle parking. Spacious areas up to 25,000 sqm.", [{ heading: "Abu Dhabi Open Yard Services", content: "Our Abu Dhabi open yards support construction companies needing equipment staging areas, logistics firms requiring vehicle parking, and businesses needing outdoor storage." }], ["open-yard-rental-uae"]),

  kw("caravan-rental-uae", "Caravan Rental UAE", "Porta Cabin & Caravan for Rent in UAE", "Rent caravans & porta cabins in UAE. Temporary offices, labor camps, site offices. A/C & drainage. Hadeed Transport.", "Hadeed Transport provides caravans and porta cabins for rent across the UAE. Ideal for temporary site offices, labor camps, and project accommodations with air conditioning.", [{ heading: "Caravan & Porta Cabin Solutions", content: "Our caravans serve as temporary offices, labor accommodations, storage units, and project control rooms. Equipped with AC, water supply, and drainage systems." }], ["mobile-toilet-rental-uae"]),

  kw("mobile-toilet-rental-uae", "Mobile Toilet Rental UAE", "Mobile Toilets for Rent in UAE", "Rent mobile toilets in Abu Dhabi & Dubai. Construction sites, events & outdoor venues. Hadeed Transport.", "Portable sanitation for construction sites, outdoor events, and temporary facilities across the UAE. Short-term and long-term mobile toilet rental available.", [{ heading: "Portable Sanitation", content: "Our mobile toilets provide clean, convenient restroom facilities for construction sites, events, and remote locations. Available for single events or long-term site placement." }], ["caravan-rental-uae"]),

  kw("storage-container-rental", "Storage Container Rental", "Storage Container for Rent in UAE", "Rent storage containers in Abu Dhabi & Dubai. Secure portable storage for sites & events. Hadeed Transport.", "Durable, secure storage containers for rent across the UAE. Ideal for construction site storage, event equipment, inventory, and general secure storage needs.", [{ heading: "Secure Portable Storage", content: "Our storage containers provide weather-resistant, secure storage that can be placed anywhere. Perfect for construction sites needing locked tool and material storage." }], ["warehouse-rental-uae"]),

  kw("industrial-space-rental", "Industrial Space Rental", "Industrial Space for Rent in UAE", "Rent industrial space in Abu Dhabi — warehouses, open yards & offices. ICAD III location. Hadeed Transport.", "Complete industrial space solutions in Abu Dhabi. Warehouses, open yards, offices, and storage facilities available in our ICAD III compound.", [{ heading: "Comprehensive Industrial Space", content: "Our ICAD III facility offers a combination of warehouses, open yards, offices, and storage — all in one convenient location for your industrial operations." }], ["warehouse-rental-uae", "open-yard-rental-uae"]),

  kw("labor-camp-rental-uae", "Labor Camp Rental UAE", "Labor Camp Accommodation Rental in UAE", "Rent labor camp facilities in UAE. Caravans & porta cabins for worker accommodation. A/C, water & drainage. Hadeed Transport.", "Set up worker accommodation quickly with our labor camp solutions. Caravans equipped with air conditioning, water supply, and drainage for comfortable worker housing.", [{ heading: "Worker Accommodation", content: "Our caravan-based labor camps provide comfortable and compliant worker accommodation. Each unit is equipped with AC, water connections, and can be configured to meet your workforce requirements." }], ["caravan-rental-uae"]),

  kw("temporary-office-rental", "Temporary Office Rental", "Temporary Office for Rent in UAE", "Rent temporary offices in UAE. Portable site offices, project offices & meeting rooms. Hadeed Transport.", "Set up your site office or project office quickly with our temporary office solutions. Air-conditioned caravans and containers configured as professional workspaces.", [{ heading: "Portable Office Solutions", content: "Our temporary offices come fully equipped with AC, electrical connections, and can be fitted out with desks, chairs, and IT infrastructure. Perfect for construction site offices and project management rooms." }], ["caravan-rental-uae", "office-space-rental-uae"]),

  // ── GENERAL SERVICE KEYWORDS (131-170) ────────────
  kw("construction-equipment-rental-uae", "Construction Equipment Rental UAE", "Construction Equipment for Rent in UAE", "Rent construction equipment in UAE — heavy machinery, tools, generators & transport. Complete project solutions. Hadeed Transport.", "Hadeed Transport is your one-stop solution for construction equipment rental in the UAE. From heavy earthmoving machinery to small hand tools, generators to transport vehicles, we have everything your project needs.", [{ heading: "Complete Equipment Solutions", content: "Why deal with multiple suppliers? Hadeed Transport provides the full spectrum of construction equipment — heavy machinery, tools, generators, transport vehicles, and temporary facilities — all from one reliable source." }, { heading: "Project-Ready Equipment", content: "Every piece of equipment is maintained, tested, and ready for immediate deployment. We deliver to your site, provide operators when needed, and offer 24/7 support." }], ["construction-equipment-rental-abu-dhabi", "construction-equipment-rental-dubai"]),

  kw("construction-equipment-rental-abu-dhabi", "Equipment Rental Abu Dhabi", "Construction Equipment Rental in Abu Dhabi", "Rent construction equipment in Abu Dhabi. Heavy machinery, tools & transport. Based in ICAD III. Same-day delivery. Hadeed Transport.", "Based in ICAD III, Hadeed Transport is Abu Dhabi's premier construction equipment rental provider. Same-day delivery of heavy machinery, tools, generators, and transport across the emirate.", [{ heading: "Abu Dhabi's Equipment Partner", content: "From our ICAD III base, we serve all Abu Dhabi areas with rapid equipment delivery. Our fleet is maintained for the demanding UAE construction environment." }], ["construction-equipment-rental-uae"]),

  kw("construction-equipment-rental-dubai", "Equipment Rental Dubai", "Construction Equipment Rental in Dubai", "Rent construction equipment in Dubai — machinery, tools, generators & transport. Delivery to all areas. Hadeed Transport.", "Full construction equipment rental services for Dubai projects. Heavy machinery, tools, generators, and transport vehicles delivered to all Dubai areas from our Abu Dhabi fleet.", [{ heading: "Dubai Project Support", content: "We serve Dubai's construction industry with our comprehensive fleet. From Al Quoz industrial areas to Dubai South mega-projects, our equipment supports projects of every scale." }], ["construction-equipment-rental-uae"]),

  kw("heavy-equipment-rental-uae", "Heavy Equipment Rental UAE", "Heavy Equipment for Rent in UAE", "Rent heavy equipment in UAE — excavators, cranes, loaders, tankers & more. Certified operators. Hadeed Transport.", "Access heavy construction equipment without the ownership burden. Hadeed Transport's fleet includes excavators, cranes, forklifts, tankers, and transport vehicles — all available for flexible rental.", [{ heading: "Heavy Equipment Fleet", content: "Our heavy equipment fleet includes shovels, backhoe loaders, mobile cranes, forklifts, manlifts, tankers, and transport vehicles. Every machine is well-maintained and ready for deployment." }], ["heavy-equipment-rental-abu-dhabi", "heavy-equipment-rental-dubai"]),

  kw("heavy-equipment-rental-abu-dhabi", "Heavy Equipment Abu Dhabi", "Heavy Equipment Rental in Abu Dhabi", "Rent heavy equipment in Abu Dhabi — complete fleet with operators. Same-day delivery. Hadeed Transport.", "Abu Dhabi's trusted heavy equipment rental provider. Excavators, cranes, forklifts, and tankers — delivered same-day from our ICAD III base with certified operators.", [{ heading: "Heavy Equipment in Abu Dhabi", content: "We support Abu Dhabi's construction and industrial sectors with reliable heavy machinery. Same-day delivery and 24/7 support keep your operations running." }], ["heavy-equipment-rental-uae"]),

  kw("heavy-equipment-rental-dubai", "Heavy Equipment Dubai", "Heavy Equipment Rental in Dubai", "Rent heavy equipment in Dubai — excavators, cranes, loaders & more. Delivery across all areas. Hadeed Transport.", "Heavy equipment rental for Dubai's booming construction sector. Excavators, cranes, forklifts, and specialized machinery delivered to all Dubai project sites.", [{ heading: "Heavy Machinery for Dubai", content: "Dubai's ambitious construction projects need reliable equipment partners. Our heavy machinery fleet supports everything from villa construction to skyscraper development." }], ["heavy-equipment-rental-uae"]),

  kw("equipment-rental-near-me", "Equipment Rental Near Me", "Construction Equipment Rental Near You in UAE", "Find construction equipment rental near you in Abu Dhabi & Dubai. Fast delivery. Hadeed Transport — serving all UAE areas.", "Looking for equipment rental near you? Hadeed Transport delivers to all areas of Abu Dhabi and Dubai. Wherever your project is, we bring the equipment to you — fast.", [{ heading: "Equipment Wherever You Are", content: "Based in ICAD III, Abu Dhabi, our fleet reaches any location across the UAE. Same-day delivery to Abu Dhabi, next-day to Dubai, and scheduled delivery to all emirates." }], ["construction-equipment-rental-uae"]),

  kw("rent-construction-tools-uae", "Rent Construction Tools", "Construction Tools for Rent in UAE", "Rent construction tools in UAE — compactors, concrete tools, generators, cutters & more. Affordable daily rates. Hadeed Transport.", "Professional construction tools available for rent at competitive rates. From concrete mixers to generators, compactors to cutting machines, rent the tools you need for your project.", [{ heading: "Wide Tool Selection", content: "Our construction tool inventory includes concrete equipment, compaction tools, generators, air compressors, cutting machines, steel processing equipment, and survey instruments." }], ["construction-equipment-rental-uae"]),

  kw("machinery-rental-uae", "Machinery Rental UAE", "Machinery Rental Services in UAE", "Rent machinery in UAE — construction, industrial & logistics equipment. Well-maintained fleet. Hadeed Transport.", "Full machinery rental services across the UAE. Construction, industrial, and logistics equipment from a trusted provider with 15+ years of experience.", [{ heading: "Machinery Rental Excellence", content: "With over 15 years of experience, Hadeed Transport has built a reputation for well-maintained machinery, reliable service, and competitive pricing across the UAE." }], ["construction-equipment-rental-uae"]),

  kw("cheap-equipment-rental-uae", "Cheap Equipment Rental UAE", "Affordable Equipment Rental in UAE", "Affordable equipment rental in Abu Dhabi & Dubai. Competitive rates, no hidden charges. Hadeed Transport.", "Quality equipment doesn't have to be expensive. Hadeed Transport offers competitive rental rates with transparent pricing — no hidden charges or surprise fees.", [{ heading: "Value Without Compromise", content: "We provide well-maintained equipment at rates that fit your budget. Long-term rentals, volume discounts, and bundled packages offer even better value." }], ["construction-equipment-rental-uae"]),

  kw("long-term-equipment-rental", "Long Term Equipment Rental", "Long-Term Equipment Rental in UAE", "Long-term equipment rental in Abu Dhabi & Dubai. Discounted monthly rates for ongoing projects. Hadeed Transport.", "Save money on long-term projects with our discounted monthly rental rates. Hadeed Transport offers favorable long-term contracts for equipment and space rentals.", [{ heading: "Long-Term Rental Benefits", content: "Our long-term rental contracts offer reduced monthly rates, priority maintenance support, and equipment guarantees. Ideal for projects spanning months or years." }], ["construction-equipment-rental-uae"]),

  kw("short-term-equipment-rental", "Short Term Equipment Rental", "Short-Term & Daily Equipment Rental in UAE", "Daily & weekly equipment rental in Abu Dhabi & Dubai. Flexible short-term rates. No long commitment. Hadeed Transport.", "Rent equipment for a day, a week, or just when you need it. Hadeed Transport offers flexible short-term rentals with no long-term commitment required.", [{ heading: "Flexible Short-Term Rental", content: "Not every project needs a long-term contract. Our daily and weekly rental options give you access to professional equipment for exactly as long as you need it." }], ["construction-equipment-rental-uae"]),

  kw("construction-vehicle-rental", "Construction Vehicle Rental", "Construction Vehicles for Rent in UAE", "Rent construction vehicles in UAE — pickups, trailers, buses, tankers & recovery trucks. Hadeed Transport.", "From 1-ton pickups to 60-seater buses, trailers to tankers — Hadeed Transport provides the construction vehicle fleet your project needs across the UAE.", [{ heading: "Construction Transport Fleet", content: "Our vehicle fleet covers every construction transport need — pickups for materials, buses for workers, tankers for water and fuel, trailers for heavy loads, and recovery trucks for equipment." }], ["pickup-truck-rental-uae", "bus-rental-uae"]),

  kw("equipment-with-operator-rental", "Equipment with Operator", "Rent Equipment with Certified Operator in UAE", "Rent equipment with certified operators in Abu Dhabi & Dubai. Safe, professional equipment operation. Hadeed Transport.", "Every piece of heavy equipment comes with the option of a certified, experienced operator. Hadeed Transport ensures safe, professional equipment operation on your project.", [{ heading: "Certified Operators Included", content: "Our operators are certified, experienced, and trained in UAE safety standards. They bring expertise that maximizes equipment productivity while maintaining strict safety protocols." }], ["construction-equipment-rental-uae"]),

  kw("equipment-delivery-uae", "Equipment Delivery UAE", "Equipment Delivery Service in UAE", "Same-day & next-day equipment delivery in Abu Dhabi & Dubai. Reliable logistics from ICAD III. Hadeed Transport.", "Reliable equipment delivery across the UAE. Same-day service in Abu Dhabi, next-day to Dubai. Our logistics team ensures your equipment arrives when and where you need it.", [{ heading: "Logistics Excellence", content: "From our ICAD III base, our logistics team coordinates equipment delivery across the UAE. GPS-tracked fleet vehicles ensure transparency and on-time arrival." }], ["construction-equipment-rental-uae"]),

  // ── SPECIALIZED TOOL KEYWORDS (171-200) ───────────
  kw("coring-machine-rental", "Coring Machine Rental", "Coring Machine for Rent in UAE", "Rent concrete coring machines in Abu Dhabi & Dubai. Diamond core drilling for precise openings. Hadeed Transport.", "Create precise openings in concrete with our diamond-bit coring machines. Available for plumbing, electrical, and HVAC installations across UAE construction projects.", [{ heading: "Diamond Core Drilling", content: "Our coring machines use diamond-tipped core bits for clean, precise cuts through concrete, brick, and masonry. Water-cooled systems prevent overheating and ensure smooth operation." }], []),

  kw("survey-equipment-rental", "Survey Equipment Rental", "Survey Equipment for Rent in UAE", "Rent survey equipment in Abu Dhabi & Dubai — total stations, auto levels & laser levels. Calibrated instruments. Hadeed Transport.", "Professional survey equipment available for rent. Total stations, auto level machines, and laser levels — all precision-calibrated for accurate construction surveys.", [{ heading: "Precision Survey Instruments", content: "Our survey equipment includes Leica total stations for precise positioning, auto level machines for elevation control, and laser levels for alignment work. All instruments are regularly calibrated." }], []),

  kw("total-station-rental", "Total Station Rental", "Total Station for Rent in UAE", "Rent Leica TC405 total station in UAE. Precision survey instrument for construction site layout. Hadeed Transport.", "The Leica TC405 total station provides precise angle and distance measurements for construction site layout, building alignment, and infrastructure surveying across the UAE.", [{ heading: "Leica Total Station", content: "Our Leica TC405 total station delivers professional-grade precision for construction surveys. Complete with tripod and accessories, calibrated and ready for site deployment." }], ["survey-equipment-rental"]),

  kw("laser-level-rental", "Laser Level Rental", "Laser Level for Rent in UAE", "Rent laser level machines in Abu Dhabi & Dubai. Construction alignment & leveling. Hadeed Transport.", "Precision laser levels for construction alignment and leveling. Ideal for grading, pipe laying, elevation control, and building construction across the UAE.", [{ heading: "Laser Level Accuracy", content: "Our laser level machines provide accurate reference lines and levels for construction operations. Self-leveling models ensure quick setup for efficient surveying." }], ["survey-equipment-rental"]),

  kw("concrete-power-float-rental", "Power Float Rental", "Concrete Power Float for Rent in UAE", "Rent concrete power floats in UAE. Professional slab finishing equipment. Hadeed Transport.", "Achieve smooth, professional concrete finishes with our power float equipment. Ideal for large slab finishing, industrial floor concrete, and commercial flooring projects.", [{ heading: "Professional Concrete Finishing", content: "Our power floats deliver smooth, level concrete surfaces for warehouses, factories, retail spaces, and any project requiring professional-grade floor finishing." }], ["concrete-equipment-rental-uae"]),

  kw("grinding-machine-rental", "Grinding Machine Rental", "Concrete Grinding Machine for Rent in UAE", "Rent concrete grinding machines in Abu Dhabi & Dubai. Surface preparation & finishing. Hadeed Transport.", "Prepare and finish concrete surfaces with our professional grinding machines. Surface leveling, polishing, and preparation for coatings across construction projects.", [{ heading: "Surface Preparation", content: "Our concrete grinding machines handle surface leveling, high-spot removal, and floor polishing. Essential for preparing concrete surfaces for epoxy coatings, tiles, or smooth finishes." }], ["concrete-equipment-rental-uae"]),

  kw("marble-cutter-rental", "Marble Cutter Rental", "Marble Cutting Machine for Rent in UAE", "Rent marble cutting machines in Abu Dhabi & Dubai. Precision cutting for tiles & stone. Hadeed Transport.", "Precision marble and stone cutting with our professional cutting machines. Clean, accurate cuts for flooring, cladding, and decorative stonework installations.", [{ heading: "Precision Stone Cutting", content: "Our marble cutting machines deliver clean, precise cuts through marble, granite, and natural stone. Water-cooled systems provide dust-free cutting with smooth edges." }], []),

  kw("wood-cutter-rental", "Wood Cutter Rental", "Electric Wood Cutter for Rent in UAE", "Rent electric wood cutters in Abu Dhabi & Dubai. Formwork & carpentry cutting equipment. Hadeed Transport.", "Professional wood cutting equipment for formwork fabrication, carpentry, and general woodworking on construction sites across the UAE.", [{ heading: "Construction Woodworking", content: "Our electric wood cutters handle formwork fabrication, scaffold board cutting, timber framing, and general carpentry tasks. Powerful motors deliver clean cuts through all timber sizes." }], []),

  kw("block-cutter-rental", "Block Cutter Rental", "Block Cutter Machine for Rent in UAE", "Rent block cutting machines in Abu Dhabi & Dubai. Precision masonry cutting. Hadeed Transport.", "Professional block cutting for masonry construction. Our machines deliver clean, precise cuts through concrete blocks, bricks, and masonry units.", [{ heading: "Masonry Block Cutting", content: "Our block cutter machines handle all standard block and brick sizes with precision. Water-cooled cutting systems ensure clean cuts and minimal dust." }], []),

  kw("plaster-machine-rental", "Plaster Machine Rental", "Plastering Machine for Rent in UAE", "Rent plastering machines in Abu Dhabi & Dubai. 5x faster than manual. Even application. Hadeed Transport.", "Speed up your plastering work by 5x with our machine plastering equipment. Even application, consistent thickness, and reduced material waste.", [{ heading: "Machine Plastering Efficiency", content: "Our plaster machines apply gypsum, cement, and lime plasters evenly and quickly. Covering 200-400 sqm per day — five times more than manual application." }], []),

  kw("construction-rental-company-uae", "Construction Rental Company", "Top Construction Rental Company in UAE", "Hadeed Transport — trusted construction equipment rental company in UAE. 15+ years, 500+ clients, certified operators.", "With 15+ years in the industry and 500+ satisfied clients, Hadeed Transport is the UAE's trusted construction equipment and space rental company. Well-maintained fleet, certified operators, competitive rates.", [{ heading: "Why Choose Hadeed Transport", content: "From heavy machinery to small tools, transport vehicles to storage facilities — we provide everything a construction project needs under one roof. Our reputation is built on reliability, quality, and fair pricing." }, { heading: "Our Track Record", content: "15+ years of service, 500+ happy clients, 1200+ projects completed. We understand the UAE construction industry and deliver solutions that keep your projects on track." }], ["construction-equipment-rental-uae"]),

  kw("equipment-rental-company-abu-dhabi", "Equipment Rental Abu Dhabi", "Best Equipment Rental Company in Abu Dhabi", "Hadeed Transport — Abu Dhabi's premier equipment rental company. Based in ICAD III. Same-day delivery. 500+ clients.", "Based in ICAD III, Hadeed Transport is Abu Dhabi's go-to equipment rental company. From heavy machinery to storage space, we serve the emirate with reliable equipment and fast delivery.", [{ heading: "Abu Dhabi's Equipment Partner", content: "Located right in Abu Dhabi's industrial heartland, we understand the local construction industry. Our proximity means faster delivery, better support, and competitive rates." }], ["construction-rental-company-uae"]),

  kw("equipment-rental-company-dubai", "Equipment Rental Dubai", "Best Equipment Rental Company for Dubai Projects", "Equipment rental for Dubai projects — Hadeed Transport. Heavy machinery, tools, generators & transport. Delivery to all areas.", "Looking for a reliable equipment rental partner for your Dubai project? Hadeed Transport delivers comprehensive construction solutions to all Dubai areas.", [{ heading: "Serving Dubai Projects", content: "Dubai's fast-paced construction industry demands responsive equipment partners. We deliver machinery, tools, and transport vehicles to all Dubai areas with reliability and speed." }], ["construction-rental-company-uae"]),

  kw("rent-equipment-online-uae", "Rent Equipment Online UAE", "Rent Equipment Online in UAE", "Rent construction equipment online in UAE. Browse catalog, get instant quote via WhatsApp. Hadeed Transport.", "Browse our equipment catalog online and request a quote instantly via WhatsApp. Hadeed Transport makes renting construction equipment in the UAE simple and fast.", [{ heading: "Easy Online Rental", content: "Browse our catalog, select what you need, and get an instant quote through WhatsApp. Our streamlined process gets equipment to your site faster than traditional rental companies." }], ["construction-equipment-rental-uae"]),

  kw("construction-machinery-hire", "Construction Machinery Hire", "Construction Machinery Hire in UAE", "Hire construction machinery in Abu Dhabi & Dubai. Excavators, cranes, generators & tools. Hadeed Transport.", "Hire professional construction machinery across the UAE. From earthmoving to lifting, power generation to material handling — Hadeed Transport has the right machine for every job.", [{ heading: "Machinery Hire Solutions", content: "Short-term hire or long-term lease — we offer flexible machinery hire options for construction companies of all sizes. Well-maintained equipment backed by 24/7 support." }], ["construction-equipment-rental-uae"]),

  kw("plant-hire-uae", "Plant Hire UAE", "Plant Hire Services in UAE", "Plant hire in Abu Dhabi & Dubai — complete construction plant including machinery, tools & temporary facilities. Hadeed Transport.", "Complete plant hire solutions for construction projects in the UAE. Machinery, tools, generators, transport, and temporary facilities — all from one trusted provider.", [{ heading: "Comprehensive Plant Hire", content: "Our plant hire service covers the full spectrum of construction needs — from the first shovel of earthwork to the final coat of plaster. One supplier, one relationship, complete solutions." }], ["construction-equipment-rental-uae"]),

  kw("construction-site-setup-uae", "Construction Site Setup", "Construction Site Setup Equipment in UAE", "Construction site setup equipment rental in UAE — generators, containers, caravans, toilets & tools. Hadeed Transport.", "Set up your construction site quickly with our comprehensive site establishment package. Generators, storage containers, site offices, mobile toilets, and initial tools — all from Hadeed Transport.", [{ heading: "Complete Site Establishment", content: "We provide everything needed to establish a functional construction site — power generation, temporary offices, worker facilities, storage, and initial equipment. One call sets up your entire site." }], ["caravan-rental-uae", "mobile-toilet-rental-uae", "generator-rental-uae"]),

  kw("project-equipment-solution-uae", "Project Equipment Solutions", "Complete Project Equipment Solutions in UAE", "Complete project equipment solutions in UAE. One supplier for all machinery, tools, transport & space needs. Hadeed Transport.", "Why manage multiple suppliers? Hadeed Transport provides complete project equipment solutions — machinery, tools, transport, generators, and space — all from one reliable partner.", [{ heading: "Single-Source Solutions", content: "Simplify your project procurement with Hadeed Transport as your single equipment source. From excavation to finishing, transportation to storage — we handle it all with consistent quality." }], ["construction-equipment-rental-uae"]),

  kw("equipment-leasing-uae", "Equipment Leasing UAE", "Equipment Leasing Services in UAE", "Equipment leasing in Abu Dhabi & Dubai. Flexible long-term rental contracts. Hadeed Transport.", "Flexible equipment leasing options for long-term projects. Competitive monthly rates, priority maintenance support, and equipment guarantees from Hadeed Transport.", [{ heading: "Leasing Advantages", content: "Leasing equipment preserves your capital while providing access to well-maintained machinery. Fixed monthly costs, included maintenance, and upgrade options make leasing smart for many projects." }], ["long-term-equipment-rental"]),

  kw("heavy-machinery-uae", "Heavy Machinery UAE", "Heavy Machinery for Rent in UAE", "Rent heavy machinery in UAE — excavators, shovels, cranes, loaders & earthmoving equipment. Hadeed Transport.", "Access the heavy machinery your project demands without the capital investment. Hadeed Transport's fleet includes the UAE's most trusted earthmoving and lifting equipment.", [{ heading: "Heavy Machinery Fleet", content: "Shovels, excavators, backhoe loaders, cranes, forklifts, and specialized machinery — our heavy fleet handles the most demanding construction operations in the UAE." }], ["heavy-equipment-rental-uae"]),

  kw("uae-rental-services", "UAE Rental Services", "Equipment & Space Rental Services in UAE", "Equipment & space rental services across UAE. Heavy machinery, tools, transport, warehouses & storage. Hadeed Transport.", "Hadeed Transport delivers equipment and space rental services across all UAE emirates. From Abu Dhabi to Dubai, from heavy machinery to warehouse space.", [{ heading: "UAE-Wide Rental Services", content: "Operating from our Abu Dhabi base, we serve projects across the UAE. Our logistics network ensures reliable delivery and support to any location in the country." }], ["construction-equipment-rental-uae"]),

  kw("abu-dhabi-industrial-equipment", "Abu Dhabi Industrial Equipment", "Industrial Equipment Rental in Abu Dhabi", "Rent industrial equipment in Abu Dhabi — machinery, generators, compressors & tools. ICAD III base. Hadeed Transport.", "Industrial-grade equipment rental from Abu Dhabi's industrial heartland. Generators, compressors, pumps, and specialized machinery for manufacturing and industrial operations.", [{ heading: "Industrial Equipment Range", content: "We serve Abu Dhabi's industrial sector with generators for power, compressors for air supply, pumps for water management, and machinery for material handling and processing." }], ["construction-equipment-rental-abu-dhabi"]),

  kw("dubai-construction-solutions", "Dubai Construction Solutions", "Construction Equipment Solutions in Dubai", "Complete construction equipment solutions for Dubai projects. Rent machinery, tools, transport & space. Hadeed Transport.", "Dubai's construction projects deserve reliable equipment partners. Hadeed Transport provides comprehensive solutions from machinery and tools to transport and temporary facilities.", [{ heading: "Dubai Construction Support", content: "From Downtown high-rises to Palm Jumeirah luxury villas, our equipment supports Dubai's diverse construction landscape. Professional fleet, competitive rates, reliable delivery." }], ["construction-equipment-rental-dubai"]),
]
